### PR TITLE
Updating example build and readme instructions

### PR DESCRIPTION
**Pull request by AndrewRayCode**
This removes a committed built file and updates the readme with build
instructions.

### CODE REVIEW

**Comment by alexlande** [comment]
Thanks @DelvarWorld! Would you mind updating this to suggest `npm run example` or `npm run build-example` instead? https://github.com/alexlande/react-style-guide/blob/master/package.json#L5-L8

**Comment by AndrewRayCode** [comment]
oooh

**Comment by AndrewRayCode** [comment]
Done, pushed -f and removed the /example path in webpack config

**Comment by alexlande** [comment]
Awesome, thanks!

**Pull request merged**
